### ISSUE TITLE
“Block entire section” for custom replacement behaves odd

### ISSUE THREAD

**Issue by acornestean** [mozilla/fireblocks#15]
Description:
Block entire section for custom replacement behaves odd.

For example, on https://fr.wikipedia.org/wiki/Jules_Ladoum%C3%A8gue enter the block phrase “10 décembre 1906“ which essentially has 3 words. For custom replacement add “1”. Once enabled the following happens:
- For custom replacement “1”. The block phrase is replaced by 1 1 1 and not just a single 1
- For custom replacement “1 2”. The block phrase is replaced by 1 2 1 and not 1 2
- For custom replacement “1 2 3”. The block phrase is replaced by 1 2 3
- For custom replacement “1 2 3 4”. The block phrase is replaced by 1 2 3 4

For the first 2 cases there is something that happens that is related to the number of words that are replaced and the number of words of the replacement.

Steps to reproduce:
1. Access https://fr.wikipedia.org/wiki/Jules_Ladoum%C3%A8gue
2. Create a rule with the block phrase “10 décembre 1906“, replace with “Text (Custom), custom Replacement “1”, replace option “Block entire section” and enable it
3. Notice the replaced words in the article - The block phrase is replaced by 1 1 1 and not just a single 1
4. Change the replacement to “1 2”
5. Notice the replaced words in the article - The block phrase is replaced by 1 2 1 and not 1 2

Actual:
The add-on does not consider the block phrase as one group that should be replaced.

Expected:
If the block phrase is comprised of, for example, 3 words and the replacement is 1 word, the 3 words should be considered as 1 group that should be replaced by the replacement.

![2023-09-22_11h22_23](https://github.com/mozilla/fireblocks/assets/50236075/19878b44-60a7-4f67-bb30-f56984af0e5c)

**Comment by GregSherman** [comment]
This is intentional and the logic is not very clear. When blocking an entire section with a replacement phrase, I have some rules

1. The replacement phrase must be shown at least once in its entirety
2. The number of words should attempt to stay the same as the original phrase's
3. The replacement phrase will repeat itself up to the number of words, at which point it stops repeating itself even if it did not finish the last repetition.

The intent is to roughly keep the size of the paragraph the same.
